### ISSUE TITLE
Circular import between px-functions-design and px-defaults-design

### ISSUE THREAD

**Issue by tingzuge** [PredixDev/px-functions-design#1]
There appears to be a circular dependency between px-functions-design and px-defaults design.

_tools.functions.scss imports px-defaults-design/_settings.defaults.scss, and _settings.defaults.scss imports px-functions-design/_tools.functions.scss.

**Comment by randyaskin** [comment]
When you run your Sass build tasks in Gulp, you need to use the `node-sass-import-once` module to stop import loops. You can do the following to accomplish this:

Install the `node-sass-import-once` as a dev dependency in your package.json

```
$ npm install —save-dev node-sass-import-once
```

Require the package in your gulpfile.js

```
var importOnce = require('node-sass-import-once');
```

Pass the sass tasks the correct options to use package. For example, for this existing task:

```
gulp.task('sass', function(cb){
    return gulp.src(paths.app.styles)
        .pipe(sass({includePaths: ['./public/bower_components/']}).on('error', sass.logError))
        .pipe(gulp.dest(paths.app.basePath + 'styles'));
});
```

You can modify the sass options you already pass to make sure you only import dependencies once:

```
gulp.task('sass', function(cb){
    return gulp.src(paths.app.styles)
        .pipe(sass({
          includePaths: ['./public/bower_components/'],
          importer: importOnce,
          importOnce: {
              index: true,
              bower: true
          }
        }).on('error', sass.logError))
        .pipe(gulp.dest(paths.app.basePath + 'styles'));
});
```

**Comment by tallaxes** [comment]
Ok, this works. I am using this in a different context (Angular 2 app), so no gulp, but I can still pass in node-sass options (via `webpack.LoaderOpertionsPlugin { sassLoader: ... }`); and it also means `includePaths` for bower_components I had in there is no longer needed.

But why circular dependencies in the first place? Is there no way to design them out? Or is it a common pattern in SASS?

**Comment by randyaskin** [comment]
No, it's probably not ideal - something we inherited from a past set of developers or possibly from inuitcss itself. We are already discussing as a team whether to possibly combine defaults and functions. Stay tuned.

**Comment by stephen-dahl** [comment]
I tried the plugin you provided but it is breaking other dependencies, if this is not fixed properly I will be forced to stop using this

**Comment by tallaxes** [comment]
Won't threaten to leave ;-), but, as another data point, `node-sass-import-once` does appear a bit flaky. One specific issue I just ran into: it can't handle SASS filenames that start with underscore (apparently a common pattern for partials in SASS world) but are referenced/imported without underscore (not sure if common, but apparently allowed) _and_ have dots in the filename, apart from extension - e.g. `@import 'settings.theme-default';` for a file named `_settings.theme-default.scss` - incidentally, a pattern that some Px-related projects use extensively. In this case `node-sass-import-once` currently does not look for and won't find the file prefixed with underscore, throwing an error. Regular SASS importer handles this just fine. I have not yet looked at what it would take to fix `node-sass-import-once` ...

**Comment by stephen-dahl** [comment]
ya, that is the issue i ran into :)

**Comment by stephen-dahl** [comment]
It took some research but i found the latest versions before this issue.

```
{
    "px-typography-design": "1.1.1",
    "px-defaults-design": "0.2.9",
    "px-functions-design": "0.2.6"
}
```

This got me compiling again.

**Comment by tallaxes** [comment]
Well, it looks like for `at-import/node-sass-import-once` there was [an attempt to fix it](https://github.com/at-import/node-sass-import-once/commit/8688109a930e6800a482dff081cafaa227036647), but it still misses relevant cases (and was not released / pushed to the public npm registry anyway). However, at least one of the forks ([`eppsilon/node-sass-import-once`](https://github.com/eppsilon/node-sass-import-once)) appears to have [gotten it right](https://github.com/eppsilon/node-sass-import-once/commit/b15879975440e09ff0e571b5a29facb19de548d0). The following works for me:

``` sh
npm install --save-dev eppsilon/node-sass-import-once#fix-importing-files-with-dots
```

This depends on github repository/branch, likely not ideal, but would work for now.

Would be nice to have better long-term solution. Apparently there may actually be some merit in enforcing/supporting import-only-once. I don't have enough experience with SASS use cases to have an opinion. If it is decided that this is the right path - probably need to make sure the canonical `node-sass-import-once` is fully functional. (Or maybe some other mechanism; [`wilsonpage/sass-import-once`](https://github.com/wilsonpage/sass-import-once)?). Otherwise need to get rid of circular dependencies ...
